services:

  proxy:
    image: traefik:v3.7
    ports:
      - "80:80"
      - "8090:8080"
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --entrypoints.http.address=:80
      - --accesslog
      - --log
      - --log.level=DEBUG
      - --api
      - --api.insecure=true
  db:
    ports:
      - "5432:5432"

  adminer:
    ports:
      - "8080:8080"

  backend:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: backend/Dockerfile
    command:
      - fastapi
      - dev
      - --host
      - "0.0.0.0"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app/backend
          ignore:
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    volumes:
      - ./backend/htmlcov:/app/backend/htmlcov
    environment:
      FASTAPI_ENV: "development"
      SMTP_HOST: "mailpit"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
