name: Deploy

on:
  push:
    branches:
      - master
    paths-ignore:
      - release-notes.md
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    # Do not deploy the template repository, only projects created from it
    if: github.repository != 'fastapi/full-stack-fastapi-template'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
        with:
          version: "latest-known"
      - name: Prepare database
        run: uv run bash scripts/prestart.sh
        working-directory: backend
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          FIRST_SUPERUSER: ${{ vars.FIRST_SUPERUSER }}
          FIRST_SUPERUSER_PASSWORD: ${{ secrets.FIRST_SUPERUSER_PASSWORD }}
      - name: Deploy to FastAPI Cloud
        run: uv run fastapi deploy
        env:
          FASTAPI_CLOUD_TOKEN: ${{ secrets.FASTAPI_CLOUD_TOKEN }}
          FASTAPI_CLOUD_APP_ID: ${{ secrets.FASTAPI_CLOUD_APP_ID }}
